### PR TITLE
Bridge Cosmos Wallet Connect

### PR DESCRIPTION
**Pull request by huydo2105**

### CODE REVIEW

**Comment by mycodecrafting** [comment]
You should override this in the cosmos wallet connect theme settings. These are somewhat elusive and difficult to find, and took me a bit of time to initially find them to color the background black. Hopefully this helps:

Theme overrides can be set here:  https://github.com/forma-dev/hyperlane-bridge-ui/blob/main/src/features/wallet/context/CosmosWalletContext.tsx#L61

What can you override? good question. There are no docs on it. But after digging a lot, I found you can get some hints here:
https://github.com/cosmology-tech/interchain-ui/blob/main/src/styles/override/override.ts#L43

From there we can dig into the `connect-modal` overrides which leads to here:  https://github.com/cosmology-tech/interchain-ui/blob/main/src/ui/connect-modal/connect-modal.helper.ts and tells us we can use the `shadow` property to override it. value of `none` should work

**Review by mycodecrafting — CHANGES_REQUESTED** [review]
see above comment

**Comment by huydo2105** [comment]
> see above comment



> You should override this in the cosmos wallet connect theme settings. These are somewhat elusive and difficult to find, and took me a bit of time to initially find them to color the background black. Hopefully this helps:
> 
> Theme overrides can be set here: https://github.com/forma-dev/hyperlane-bridge-ui/blob/main/src/features/wallet/context/CosmosWalletContext.tsx#L61
> 
> What can you override? good question. There are no docs on it. But after digging a lot, I found you can get some hints here: https://github.com/cosmology-tech/interchain-ui/blob/main/src/styles/override/override.ts#L43
> 
> From there we can dig into the `connect-modal` overrides which leads to here: https://github.com/cosmology-tech/interchain-ui/blob/main/src/ui/connect-modal/connect-modal.helper.ts and tells us we can use the `shadow` property to override it. value of `none` should work



> see above comment

image

The shadow property works for the outside box instead ( See image as I overrides shadow properties). As I check, we can only overrides following properties: background, shadow, color and borderColor.

**Review by mycodecrafting — APPROVED** [review]
Don't love this as there is no guarantee that the generated css class `.x1bv961` won't change over time, but with very limited options for customizing the cosmos modal I think this is the best we can do for now

**Pull request merged**
